pipeline {
	agent any

	environment {
		dockerImage = ''
		registry = 'feifeiliang/account-service-img'
		registryCredential='dockerid'
	}

	tools{
		maven "maven"
	}
	stages {
		stage('Build') {
			steps {
				// dir('/account-service/')
				sh "pwd"
				dir('account-service/') {
					sh 'mvn --version'
					sh 'mvn clean install -Dmaven.test.skip=true'
				}
				
				// -f account-service/pom.xml
			}
		}
		stage('Build Docker Image') {
			steps {
				script{
					sh "pwd"
					dir('account-service/') {
						dockerImage = docker.build registry
					}
				}
			}
		}
		stage ('Uploading Image'){
			steps {
				script {
					sh "pwd"
					docker.withRegistry('', registryCredential){
						dockerImage.push()
					}

				}
			}
		}

		 // Stopping Docker containers for cleaner Docker run
     	stage('docker stop container') {
         	steps {
            	sh 'docker ps -f name=accountServiceContainer -q | xargs --no-run-if-empty docker container stop'
            	sh 'docker container ls -a -fname=accountServiceContainer -q | xargs -r docker container rm'
         }
       }
        // Running Docker container, make sure port 8096 is opened in 
    	stage('Docker Run') {
     		steps{
         		script {
            		dockerImage.run("-p 8097:9003 --rm --name accountServiceContainer")
         		}
      		}
    	}

	}

	post {
		always {
			cleanWs()
		}
	}
}