pipeline {
	agent any
	tools{
		maven "maven"
	}
	stages {
		stage('Build') {
			steps {
				sh 'mvn --version'
				sh 'mvn clean install -f booking-service/pom.xml'
			}
		}
	}

	post {
		always {
			cleanWs()
		}
	}
}