pipeline {
	agent {
		dockerfile true
	}

	environment {
		dockerImage = ''
		registry = 'feifeiliang/booking-service-img'
		registryCredential='dockerhub'
	}

	tools{
		maven "maven"
	}
	stages {
		stage('Build') {
			steps {
				sh 'mvn --version'
				sh 'mvn clean install -f booking-service/pom.xml'
			}
		}
		stage('Build Docker Image') {
			steps {
				script{
					dockerImage = docker.build registry
				}
			}
		}
		stage ('Uploading Image'){
			steps {
				script {
					docker.withRegistry('', registryCredential){
						dockerImage.push()
					}

				}
			}
		}
	}

	post {
		always {
			cleanWs()
		}
	}
}